# Generated by Django 4.2.17 on 2025-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterPredictionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterprediction',
            name='confidence_score',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disasterprediction',
            name='humidity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disasterprediction',
            name='rainfall',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disasterprediction',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disasterprediction',
            name='wind_speed',
            field=models.CharField(max_length=50),
        ),
    ]
