# Generated by Django 4.2.17 on 2025-01-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasterPredictionApp', '0002_alter_disasterprediction_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('responsible_entity', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=50)),
                ('current_conditions', models.JSONField(blank=True, null=True)),
                ('risk_assessment', models.JSONField(blank=True, null=True)),
                ('implementation_timeline', models.JSONField(blank=True, null=True)),
                ('resource_requirements', models.JSONField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='disasterPredictionApp.disasterprediction')),
            ],
        ),
    ]
