# Generated by Django 4.2.17 on 2025-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasterPreventionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventionstrategy',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
